### PR TITLE
Create zh_CN file

### PR DESCRIPTION
**Pull request by TartaricAcid**
Add a Chinese language file

### CODE REVIEW

**Comment by Gollorum** [comment]
Thanks! I don't speak chinese, but after using Google Translate, I assume that this is correct, so it will be included in the next update :D

**Comment by TartaricAcid** [comment]
Thank you a lot. :+1:

**Comment by Gollorum** [comment]
Hi, update 1.02 will be released soon and it will add a few lines to the language files. I pushed the us_US.lang for the 1.7.10 version, so you can translate them too, if you want to.

**Comment by Gollorum** [comment]
*en_US

**Comment by TartaricAcid** [comment]
Thank you,  I'll do it right now.

**Pull request merged**
